apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: postgres-backup
spec:
  schedule: "0 1 * * *"  # At 01:00 AM every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: 10.0.2.4:5000/postgres-backup:v1.1
            env:
              - name: DB_HOST
                value: db-postgresql
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: postgres.db-postgresql.credentials.postgresql.acid.zalan.do
                    key: username
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres.db-postgresql.credentials.postgresql.acid.zalan.do
                    key: password
            volumeMounts:
              - name: backup-volume
                mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: worker-01-postgresql-backup
