apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-01-postgresql-backup
  labels:
    type: shared
spec:
  storageClassName: backup-storage-postgresql
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs_backup_share/Postgresql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgr-k8s-worker-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-02-postgresql-backup
  labels:
    type: shared
spec:
  storageClassName: backup-storage-postgresql
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs_backup_share/Postgresql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgr-k8s-worker-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-03-postgresql-backup
  labels:
    type: shared
spec:
  storageClassName: backup-storage-postgresql
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs_backup_share/Postgresql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgr-k8s-worker-03
