apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: worker-01-postgresql-backup
  namespace: postgres-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: backup-storage-postgresql
  volumeMode: Filesystem
  #  volumeName: worker-01-postgresql-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: worker-02-postgresql-backup
  namespace: postgres-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: backup-storage-postgresql
  volumeMode: Filesystem
  #  volumeName: worker-02-postgresql-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: worker-03-postgresql-backup
  namespace: postgres-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: backup-storage-postgresql
  volumeMode: Filesystem
  #  volumeName: worker-03-postgresql-backup
