apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-hunter
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kube-hunter
        spec:
          containers:
            - name: kube-hunter
              image: aquasec/kube-hunter:latest
              command: ["kube-hunter"]
              args: ["--pod"]
          restartPolicy: Never
