apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-01-postgresql
  labels:
    type: local
spec:
  storageClassName: local-storage-postgresql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgr-k8s-worker-01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-02-postgresql
  labels:
    type: local
spec:
  storageClassName: local-storage-postgresql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgr-k8s-worker-02