#firstly install zalando-postgres-operator: kubectl apply -k github.com/zalando/postgres-operator/manifests
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: "db-postgresql"
  namespace: "default"
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 2
  volume:
    size: "10Gi"
    storageClass: "local-storage-postgresql"
  users:
    zalando:
      - superuser
      - createdb
  databases:
    zalando: zalando
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi