#firstly install operator with:
#kubectl create -f https://download.elastic.co/downloads/eck/2.12.1/crds.yaml
#kubectl apply -f https://download.elastic.co/downloads/eck/2.12.1/operator.yaml
#then set "vm.max_map_count" in file "/etc/sysctl.conf" to "262144", save, and: "sudo sysctl -p"
#
#BACKUP - repo and slm config
#1.curl -X PUT "http://localhost:9200/_snapshot/elastic-repository" -H 'Content-Type: application/json' -d'{"type": "fs","settings": {"location": "/usr/share/elasticsearch/backup","compress": true}}' -u elastic:$PASSWORD
#2.curl -X PUT "http://localhost:9200/_slm/policy/daily_snapshots" -H 'Content-Type: application/json' -d'{"schedule": "0 30 1 * * ?","name": "<daily-snapshot-{now/d}>","repository": "elastic-repository","config": {"indices": ["*"],"ignore_unavailable": false,"include_global_state": true},"retention": {"expire_after": "30d","min_count": 1,"max_count": 50}}' -u elastic:$PASSWORD
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: default
spec:
  version: "8.13.0"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: master
      count: 1
      config:
        node.roles: ["master"]
        path.repo: ["/usr/share/elasticsearch/backup"]
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 2Gi
                  cpu: 500m
                requests:
                  memory: 2Gi
                  cpu: 200m
              volumeMounts:
                - name: elasticsearch-backup-master
                  mountPath: "/usr/share/elasticsearch/backup"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
            storageClassName: "local-storage-elasticsearch-master"
        - metadata:
            name: elasticsearch-backup-master
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
            storageClassName: "backup-storage-elasticsearch-master"
    - name: data
      count: 1
      config:
        node.roles: ["data"]
        path.repo: ["/usr/share/elasticsearch/backup"]
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 4Gi
                  cpu: 1
                requests:
                  memory: 2Gi
                  cpu: 200m
              volumeMounts:
                - name: elasticsearch-backup-data
                  mountPath: "/usr/share/elasticsearch/backup"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
            storageClassName: "local-storage-elasticsearch-data"
        - metadata:
            name: elasticsearch-backup-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
            storageClassName: "backup-storage-elasticsearch-data"