# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
[all]
mgr-k8s-master-01
mgr-k8s-worker-01
mgr-k8s-worker-02
mgr-k8s-worker-03

[kube_control_plane]
mgr-k8s-master-01

[etcd]
mgr-k8s-master-01

[kube_node]
mgr-k8s-worker-01
mgr-k8s-worker-02
mgr-k8s-worker-03

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr
