apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-critical-threat
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    critical-threat:
      endpoint: /critical-threat
      method: POST
      port: "12000"
      type: notification

