apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-argo.yaml
  - namespace-argo-events.yaml
  - rbac-workflows.yaml
  - argo-workflows.yaml
  - argo-events.yaml
  - eventbus.yaml
  - eventSource.yaml
  - rbac-delete-pod-sensor.yaml
  - rbac-wf-template-delete-pod.yaml
  - wf-template-delete-pod.yaml
  - sensor-netcat-rce.yaml
