---
- name: Update and upgrade all packages on Ubuntu/Debian
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: 'yes'
        force_apt_get: yes
        cache_valid_time: 3600  # Optional: Only update the cache if it is older than 3600 seconds (1 hour)

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the machine if required
      reboot:
        msg: "Rebooting because of a kernel update"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 0
        test_command: uptime
      when: reboot_required_file.stat.exists

